# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-01 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20170702_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='./static/uploads/%Y/%m/%d/orig'),
        ),
    ]
