# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-02 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_auto_20170702_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='./photos/uploads/%Y/%m/%d/orig'),
        ),
    ]
